name: Download Artifacts

on:
  workflow_run:
    workflows: ["MSBuild"]
    types:
      - completed

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List Files
      run: |
        ls -R $GITHUB_WORKSPACE
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: MyBuildArtifacts
        path: ${{env.GITHUB_WORKSPACE}}\src\Release\pol.dll
